fkanehiro/choreonoid-sdfloader-plugin

CMakeLists.txt, package.xml
ROSのcatkinパッケージとしてビルドできるようにしました。
=> add setting to build under catkin environment

SDFBodyLoader.cpp
sdfの絶対座標からvrmlの相対座標への変換の部分でアフィン行列を使うように変更しました。
=> use affine matrix to improve abs to rel conversion stability

SDFBodyLoader.cpp
いろいろなパターンのSDFの読み込みを安定化させるための変更です。
=> set default pose and handling of use_parent_model_frame option

SDFBodyLoader.cpp
=> copy phisical property to root link (ref #8)

SDFBodyLoader.cpp
NULL 参照が発生する可能性がある箇所と、発生した場合に問題になりそうな箇所にガードコードを追加しました。
=> add guard code

SDFBodyLoader.cpp
メッシュが複数存在する場合の対応が無かったため修正しました。
=> fix process of meshes

SDFBodyLoader.cpp
モデルのサーチパスに環境変数 GAZEBO_MODEL_PATH の値を追加するようにしました。
=> add model search path (GAZEBO_MODEL_PATH)

SDFBodyLoader.cpp
プリミティブな型の Shape において、座標と回転の設定誤りを修正しました。
=> fix process of shape

SDFBodyLoader.cpp
関節の可動範囲の設定誤りを修正しました。
併せてコンソールへのメッセージ出力を抑制しました。
=> fix joint limit range setting and message output

SDFBodyLoader.cpp
ルートジョイントの設定において、親のリンクが world でジョイント設定が固定ジョイント設定以外の場合においても、常に固定ジョイント設定となる問題を修正しました。
=> fix process of root joint

SDFBodyLoader.cpp
=> fix comiple error

SDFLoaderPseudoGazeboColor.cpp
=> fix bug in find color map

CMakeLists.txt, SDFBodyLoader.cpp, SDFSensorConverter.cpp, SDFSensorConverter.h
sdformat のデフォルトセンサ種別の内、camera、depth、force_torque、gpu_ray、imu、multicamera、ray を、Choreonoid で使用できるようにしました。
=> support the part of sensor of SDF default type.

README.ja.md
=> add README.ja.md

SDFBodyLoader.cpp
プリミティブ型 shape への pose 設定の rotation 指定が反映されない不具合を修正しました。
=> fixes the problem that primitive shape's attitude is not reflected

SDFBodyLoader.cpp
SDF のリンク・ジョイント情報を、Choreonoid のリンク情報 (cnoid::Link) へ変換する為に使用する、SDF のリンク・ジョイント情報を保持するクラス (LinkInfo, JointInfo) のメンバ変数の初期値を、cnoid::Link の初期値に合わせました。
=> initialize member variables for LinkInfo and JointInfo

SDFBodyLoader.cpp
=> fix texture loading problem

SDFBodyLoader.cpp, SDFBodyLoader.h
Choreonoid のリファクタリング (https://github.com/s-nakaoka/choreonoid/commit/964e111b8a46d6a3a181d062e8d3d27cc3e66f53) への追従を実施しました。
=> adapts to Choreonoid's refactoring (964e111)

SDFBodyLoader.cpp
SDF読み込み部分をデバッグしPR2モデルのような循環構造があるものも読み込み可能にしました。
DaeLoaderのメモリリークの影響に対応するためだと思うのですが、private関数内で冗長なNULLチェックが入っていた部分が今は安定していて不要だと思うので整理しました。
=> debug and refactor SDF loading

SDFBodyLoader.cpp
SDFからVRMLの木構造に変換するアルゴリズムを見直しました。
=> improve SDF to VRML conversion algorithm

SDFBodyLoader.cpp
PR2の頭のセンサリンクを正常な大きさで表示するための修正です。
=> consider scale parameter when reading stl mesh

SDFBodyLoader.cpp
=> line and transparency in dae file

SDFBodyLoader.cpp
Collada の処理時に SDF で指定された scale 要素を反映するようにしました。
=> fixes the collada scaling

SDFBodyLoader.cpp
issのモデルなどで問題になる、model宣言直下にあるpose宣言に対応しました。
=> fix for root pose definition
